from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('blink-settings=imagesEnabled=false')
chrome_options.add_argument('–headless')
chrome_options.add_argument('–disable-gpu')
chrome_options.add_argument('–no-sandbox')
chrome_options.add_argument('–disable-dev-shm-usage')
chrome_options.add_argument('–disable-extensions')
driver = webdriver.Chrome(options=chrome_options)
driver.get('http://www.baidu.com')
